# Updated : 2024.12.23
# Version : 1.2.5
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  board_chip: "ESP32-S3"
  board_name: "LilyGo T-Display"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB # ajust according to your ESP32-S3 version
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio             # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing
    board_upload.maximum_ram_size: 524288   # total size of the internal RAM in bits, it's the same for all ESP32-S3 ( 512KB )
    
  on_boot:
    then:
      - light.turn_on:
          id: esp_light
          red: 50%
          blue: 0%
          green: 0%
          brightness: 30%

# PSRAM activation and settings
psram:
  mode: octal
  speed: 80MHz

# <<: !include board_psram_settings.yaml

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  ap:
    ssid: "YamBMS Fallback Hotspot"
    password: "Y4mBM$85"

captive_portal:

logger:
  # baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
  # hardware_uart: USB_SERIAL_JTAG

uart:
  # UART 0 : USB UART port used for ESP32 flashing and logs, can be released if necessary (tx_pin: 43, rx_pin: 44)
  # UART 1
  - id: uart_esp_1
    tx_pin: 17
    rx_pin: 18
    baud_rate: 115200
    rx_buffer_size: 512

canbus:
  # CANBUS NODE 1
  - platform: mcp2515
    id: canbus_node1
    spi_id: bus_spi1
    cs_pin: 21
    can_id: 1
    bit_rate: 500kbps

spi:
  id: bus_spi1
  clk_pin: 12
  mosi_pin: 11
  miso_pin: 13
